version: '3'
services:
  redis-node-1:
    image: chef/node:centos
    container_name: redis-node-1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    hostname: redis-node-1
    ports:
      - "3001:6379"
      - "2201:22"
    volumes:
      - /opt/kickstart-chef/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-chef/supervisor/conf/sshd.ini:/etc/supervisord.d/sshd.ini
      - /opt/kickstart-chef/supervisor/conf/chef-push-jobs-client.ini:/etc/supervisord.d/chef-push-jobs-client.ini
    extra_hosts:
      - "chef-server:100.1.1.0"
    networks:
      - chef-stack
  redis-node-2:
    image: chef/node:centos
    container_name: redis-node-2
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    hostname: redis-node-2
    ports:
      - "3002:6379"
      - "2202:22"
    volumes:
      - /opt/kickstart-chef/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-chef/supervisor/conf/sshd.ini:/etc/supervisord.d/sshd.ini
      - /opt/kickstart-chef/supervisor/conf/chef-push-jobs-client.ini:/etc/supervisord.d/chef-push-jobs-client.ini
    extra_hosts:
      - "chef-server:100.1.1.0"
    networks:
      - chef-stack
  redis-node-3:
    image: chef/node:centos
    container_name: redis-node-3
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    hostname: redis-node-3
    ports:
      - "3003:6379"
      - "2203:22"
    volumes:
      - /opt/kickstart-chef/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-chef/supervisor/conf/sshd.ini:/etc/supervisord.d/sshd.ini
      - /opt/kickstart-chef/supervisor/conf/chef-push-jobs-client.ini:/etc/supervisord.d/chef-push-jobs-client.ini
    extra_hosts:
      - "chef-server:100.1.1.0"
    networks:
      - chef-stack
networks:
  chef-stack:
    external:
      name: chef-stack